class MyKeys{
  static const String tmdbApiKey = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNTE0YTA1OGY0NGE4Yjk0ZGYzMTJkODRiZWM2MjA2YiIsIm5iZiI6MTY5NjMyMjgwMy4xNjEsInN1YiI6IjY1MWJkNGYzMjIzYThiMDEzZGY2OTEyNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.rWgJj6BDahCnj34vxCj8daSC-CI0e-rxTDPtNzb7yrA';
  // ...
}